baseURL = "https://mobility-guide.netlify.app/"
languageCode = "en-us"
title = "Badwater Mobility"
theme = "hugo-theme-relearn"

[params]
  themeVariant = ["mobility"]
  alwaysopen = false
  disableLandingPageButton = true
  showVisitedLinks = false
  disableInlineCopyToClipBoard = true

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[taxonomies]
  tag = "tags"
